global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
#  - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8080']

    basic_auth:
      username: "admin"
      password: "pass"